CREATE TABLE SCOTT.TALK_MEMBER
(
  MEM_ID       VARCHAR2(10 BYTE),
  MEM_PW       VARCHAR2(10 BYTE),
  NICKNAME     VARCHAR2(20 BYTE),
  GENDER       VARCHAR2(1 BYTE),
  MEM_NAME     VARCHAR2(30 BYTE),
  BIRTHDAY     VARCHAR2(20 BYTE),
  PRO_PICTURE  VARCHAR2(50 BYTE),
  STATUS_MSG   VARCHAR2(500 BYTE),
  COMMAND      VARCHAR2(50 BYTE),
  MEM_HP       VARCHAR2(20 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN SCOTT.TALK_MEMBER.MEM_HP IS '전화번호';



CREATE UNIQUE INDEX SCOTT.TMEMBER_ID_PK ON SCOTT.TALK_MEMBER
(MEM_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE SCOTT.TALK_MEMBER ADD (
  CONSTRAINT TMEMBER_ID_PK
  PRIMARY KEY
  (MEM_ID)
  USING INDEX SCOTT.TMEMBER_ID_PK
  ENABLE VALIDATE);
  
edit talk_member;

commit;